name: {{project_name}}
description: A new Flutter project using BLoC pattern.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  flutter_lints: ^2.0.0
